### ISSUE TITLE
Need to help understanding how this works

### ISSUE THREAD

**Issue by heyddi** [Label84/laravel-active-campaign#4]
Hi!

I previously installed ActiveCampaign in another php framework with the AC php wrapper. But I need to install this in Laravel now and this package seems interesting. I do have a few questions:

- From the document (and the code), it seems like settings a value to a custom field requires the id of the field. But why would I list my custom fields in the config file if we are not using those ids? (I am probably missing one step)
- Can I only set values on custom fields 1 by 1? It doesn't seems like I can create the contact with the custom fields, nor can I send multiple values at the same time?

Thanks for your help !

Ed

**Comment by tjardoo** [comment]
Hi. You don't have to add your custom fields ids to the config file, this is optional. However I do like to use ``config('active-campaign.custom_fields.is_email_verified')`` instead of the number ie. 50. That makes ny code more readable and I can make sure I don't use the wrong/same id anywhere else.

It is not yet possible to set multiple custom field values at the same time. If you want you can create a PR for this. If there are more people wanting this I'm willing to add it. Thanks.
